set background=dark
set history=10000
set encoding=utf-8
scriptencoding utf-8
set laststatus=2
set colorcolumn=81
set mouse=
set ttymouse=
set nowrap
set nu
set ruler
set visualbell
set noerrorbells
set showmatch
set showmode
set autoindent
set smartindent
set incsearch
set nohlsearch
set nobackup
set nowritebackup
set noswapfile
set autoread
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set splitright
set splitbelow
set title
set report=0
set showtabline=2
syntax on
filetype on
filetype indent on
filetype plugin indent on
